### ISSUE TITLE
Editor not visible

### ISSUE THREAD

**Issue by robiso** [mjuksel/wondercms-monaco#1]
Tested on Firefox 73.0.1 and WonderCMS 3.0.6.
Also replied at your original thread: https://www.wondercms.com/forum/viewtopic.php?f=23&p=2601#p2601

Screenshots look good 🚀

**Comment by mjuksel** [comment]
Pushed a typo :D fixed.

**Comment by robiso** [comment]
@mjuksel didn't see this message until I went through all of missed messages.
Sorry for that!

Anyhow, we've just updated WonderCMS to 3.2.0 and this plugin works perfectly with it.
We'll be adding it to the official list of plugins, meaning all users will be able to install this through their WonderCMS Settings -> Plugins.

I'll be creating a fork within the next few minutes to change the description, as it wasn't immediately clear that I have to press CTRL+S to save the content. :)

Great job and thank you for contributing! Can you please share your first/last name, so we can add it to https://www.wondercms.com/contributors

**Comment by mjuksel** [comment]
@robiso Well heya!
Marcel Portma is my full name :)

About the description, should I change it instead?
I guess mentioning it's per editor is what you're after?

**Comment by robiso** [comment]
@mjuksel already forked it and added to official list or repositories :)

I forgot to ask you for your website, so we can also link to it. Can you please share that as well? 

> I guess mentioning it's per editor is what you're after?
Merely just mentioned that it needs to save with CTRL + S as you can see here in the summar file.
- https://github.com/robiso/monaco-editor

Once you share you're website, you'll be added soon. Thank you again for your contribution.

Hope 2022 is treating you well!

**Comment by mjuksel** [comment]
@robiso https://mjxl.net! 👍

**Comment by robiso** [comment]
@mjuksel thank you, added to: https://www.wondercms.com/contributors
This was a pleasure dealing with :)

**Comment by mjuksel** [comment]
@robiso tyvm! 👍 

Likewise, loving the product still hehe!
All the best the coming year for you and everyone else. Let's make it a fruitful one!
